//
// Created by Даник 💪 on 06.05.2023.
//

#ifndef LABWORK_12_KATSUSHOOTER_SRC_STRUCTURES_ATTRIBUTES_H_
#define LABWORK_12_KATSUSHOOTER_SRC_STRUCTURES_ATTRIBUTES_H_

enum Attributes {
  PRIMARY_KEY,
  FOREIGN_KEY,
  NOT_NULL
};

#endif //LABWORK_12_KATSUSHOOTER_SRC_STRUCTURES_ATTRIBUTES_H_
