//
// Created by Даник 💪 on 14.05.2023.
//

#ifndef LABWORK_12_KATSUSHOOTER_SRC_DB_STRUCTURES_JOINTYPE_H_
#define LABWORK_12_KATSUSHOOTER_SRC_DB_STRUCTURES_JOINTYPE_H_

enum JoinType {
  JOIN_LEFT,
  JOIN_RIGHT,
  JOIN_INNER
};

#endif //LABWORK_12_KATSUSHOOTER_SRC_DB_STRUCTURES_JOINTYPE_H_
